#!/usr/bin/env python3
"""
Populate Licenses Script

Imports license keys generated by create_license.py into the licensing server database.
"""

import asyncio
import asyncpg
import os
import json
import base64
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()


def decode_license_key(license_key: str) -> dict:
    """
    Decode a license key to extract the JSON payload.

    Format: base64(json_data).base64(signature)
    """
    try:
        # Split at the period
        parts = license_key.split('.')
        if len(parts) != 2:
            raise ValueError("Invalid license key format (expected 2 parts)")

        json_b64, sig_b64 = parts

        # Decode the JSON part
        json_bytes = base64.b64decode(json_b64)
        license_data = json.loads(json_bytes.decode('utf-8'))

        return license_data
    except Exception as e:
        raise ValueError(f"Failed to decode license key: {e}")


async def populate_license(conn, license_key: str) -> bool:
    """
    Add a single license to the database.

    Returns True if successful, False if already exists.
    """
    try:
        # Decode the license key to get the data
        license_data = decode_license_key(license_key)

        license_id = license_data['license_id']
        customer = license_data['customer']
        tier = license_data['tier']
        issued_at = datetime.fromisoformat(license_data['issued_at'])
        expires_at = datetime.fromisoformat(license_data['expires_at']) if license_data.get('expires_at') else None

        # Check if license already exists
        exists = await conn.fetchval(
            "SELECT EXISTS(SELECT 1 FROM licenses WHERE license_id = $1)",
            license_id
        )

        if exists:
            print(f"  ⊘ {license_id} already exists, skipping")
            return False

        # Insert the license
        await conn.execute(
            """
            INSERT INTO licenses
                (license_key, license_id, customer_name, customer_email,
                 customer_company, tier, issued_at, expires_at,
                 max_installations, created_at, updated_at)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
            """,
            license_key,
            license_id,
            customer['name'],
            customer['email'],
            customer.get('company', ''),
            tier,
            issued_at,
            expires_at,
            1  # Default to 1 installation
        )

        print(f"  ✓ Added {license_id} ({tier} tier, {customer['name']})")
        return True

    except Exception as e:
        print(f"  ✗ Error adding license: {e}")
        return False


async def populate_from_file(filepath: str):
    """
    Populate licenses from a file.

    File format: one license key per line
    """
    database_url = os.getenv("DATABASE_URL")

    if not database_url:
        print("ERROR: DATABASE_URL environment variable not set")
        return

    if not os.path.exists(filepath):
        print(f"ERROR: File not found: {filepath}")
        return

    print(f"Reading license keys from: {filepath}")

    with open(filepath, 'r') as f:
        license_keys = [line.strip() for line in f if line.strip() and not line.startswith('#')]

    print(f"Found {len(license_keys)} license keys")
    print("")

    conn = await asyncpg.connect(database_url)

    try:
        added = 0
        skipped = 0
        errors = 0

        for license_key in license_keys:
            result = await populate_license(conn, license_key)
            if result is True:
                added += 1
            elif result is False:
                skipped += 1
            else:
                errors += 1

        print("")
        print("=" * 60)
        print(f"Import complete!")
        print(f"  Added: {added}")
        print(f"  Skipped (already exist): {skipped}")
        print(f"  Errors: {errors}")
        print("=" * 60)

    finally:
        await conn.close()


async def populate_single(license_key: str):
    """Populate a single license key"""
    database_url = os.getenv("DATABASE_URL")

    if not database_url:
        print("ERROR: DATABASE_URL environment variable not set")
        return

    conn = await asyncpg.connect(database_url)

    try:
        await populate_license(conn, license_key)
    finally:
        await conn.close()


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage:")
        print("  python populate_licenses.py <license_key>")
        print("  python populate_licenses.py --file <filepath>")
        print("")
        print("Examples:")
        print("  python populate_licenses.py eyJsaWNlbnNlX2lkIjoi...")
        print("  python populate_licenses.py --file licenses.txt")
        sys.exit(1)

    if sys.argv[1] == '--file':
        if len(sys.argv) < 3:
            print("ERROR: Please specify a file path")
            sys.exit(1)
        asyncio.run(populate_from_file(sys.argv[2]))
    else:
        asyncio.run(populate_single(sys.argv[1]))
